/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.freewheel;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Random;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollProxy;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.proxy.TiViewProxy;
import org.appcelerator.titanium.util.Log;
import org.appcelerator.titanium.util.TiConfig;

import android.app.Activity;
import android.content.Context;
import android.location.Criteria;
import android.location.Location;
import android.location.LocationManager;
import android.os.Handler;
import android.os.Message;
import android.view.View;

import ti.modules.titanium.media.VideoPlayerProxy;
import tv.freewheel.ad.factories.AdManagerLoaderFactory;
import tv.freewheel.ad.interfaces.IAdContext;
import tv.freewheel.ad.interfaces.IAdManager;
import tv.freewheel.ad.interfaces.IAdManagerLoader;
import tv.freewheel.ad.interfaces.IConstants;
import tv.freewheel.ad.interfaces.IEvent;
import tv.freewheel.ad.interfaces.IEventListener;
import tv.freewheel.ad.interfaces.ISlot;
import tv.freewheel.loader.AdManagerLoader;
import tv.freewheel.loader.utils.Logger;

// This proxy can be created by calling Freewheel.createExample({message: "hello world"})
@Kroll.proxy(creatableInModule = FreewheelModule.class)
public class AdManagerProxy extends KrollProxy {

	// Standard Debugging variables
	private static final String LCAT = "FreewheelModule";
	private static final boolean DBG = TiConfig.LOGD;

	// TODO: should this really be hard coded like this?
	public static final String ADMANAGER_URL = "http://adm.fwmrm.net/p/android_tutorial/AdManager.fpk";

	private int networkId;
	private String serverUrl;

	private IAdManagerLoader adManagerLoader;
	protected IAdManager adManager;
	private IAdContext adContext;

	private String currentContentUrl;
	private int currentFallbackId;
	private TiViewProxy currentBase;
	private TiViewProxy currentCompanionBase;
	private VideoPlayerProxy currentPlayer;
	private String currentSiteSection;
	private String currentVideoId;
	private String currentProfile;

	// Constructor
	public AdManagerProxy() {
		super();
	}

	// Handle creation options
	@Override
	public void handleCreationDict(KrollDict options) {
		super.handleCreationDict(options);

		networkId = options.getInt("networkId");
		serverUrl = options.getString("serverUrl");

		adManagerLoader = AdManagerLoaderFactory.getInstance(getActivity());

		adManagerLoader.loadAdManager(ADMANAGER_URL, new Handler() {

			public void handleMessage(final Message msg) {
				Log.d(LCAT, "onAdManagerLoadedHanlder");
				boolean success = msg.getData().getBoolean("success");

				if (success) {
					onAdManagerLoaded();
				} else {
					Log.e(LCAT, "ad manager failed to load!");
				}
			}
		});
	}

	private KrollDict[] loadSlot(int position) {
		ArrayList<ISlot> slots = adContext.getSlotsByTimePositionClass(position);
		KrollDict[] retVal = new KrollDict[slots.size()];
		for (int i = 0; i < slots.size(); i++) {
			ISlot slot = slots.get(i);
			retVal[i] = new KrollDict();
			retVal[i].put("time", slot.getTimePosition());
			retVal[i].put("customId", slot.getCustomId());
		}
		return retVal;
	}

	private void onAdManagerLoaded() {
		adManager = adManagerLoader.newAdManager();

		if (adManager == null) {
			Log.e(LCAT, "ad manager failed to load!");
			return;
		}

		adManager.setLocation(getLocationInfo());
		adManager.setServer(serverUrl);
		adManager.setNetwork(networkId);
	}

	private Location getLocationInfo() {
		LocationManager locationManager = (LocationManager) getActivity().getSystemService(Context.LOCATION_SERVICE);
		String bestProvider = locationManager.getBestProvider(new Criteria(), false);
		return locationManager.getLastKnownLocation(bestProvider);
	}

	@Kroll.method(runOnUiThread = true)
	public void setAdContext(KrollDict args) {
		currentContentUrl = args.getString("contentUrl");
		currentFallbackId = args.getInt("fallbackId");

		currentBase = (TiViewProxy) args.get("base");
		currentCompanionBase = (TiViewProxy) args.get("companionBase");

		currentPlayer = (VideoPlayerProxy) args.get("player");

		currentSiteSection = args.getString("siteSection");
		currentVideoId = args.getString("videoId");
		currentProfile = args.getString("profile");

		if (DBG) {
			for (String key : args.keySet()) {
				Log.d(LCAT, key + " is set on " + args.get(key));
			}
			Log.d(LCAT, "Set current player and created ad context");
		}

		createAdContext();
	}

	private void createAdContext() {

		adContext = adManager.newContext();
		adContext.setActivity(getActivity());

		final IConstants adConstants = adContext.getConstants();

		// TODO: I have no idea what these next couple set and adds need to be...
		adContext.addKeyValue("contentUrl", currentContentUrl);

		adContext.setProfile(currentProfile, null, null, null);
		adContext.setSiteSection(currentSiteSection, 0, networkId, adConstants.ID_TYPE_CUSTOM(), 0);
		adContext.setVideoAsset(currentVideoId, 0, null, true, 0, networkId, adConstants.ID_TYPE_CUSTOM(), currentFallbackId);

		// TODO: the iOS module sets several "COUNTDOWN_TIMER_* parameters that are not exposed on Android
		adContext.setParameter(adConstants.PARAMETER_DISPLAY_AD_HTML_CONTENT_CLICK_PROCESSING(), false, adConstants.PARAMETER_LEVEL_OVERRIDE());

		adContext.addEventListener(adConstants.EVENT_REQUEST_COMPLETE(), new IEventListener() {
			public void run(final IEvent event) {
				KrollDict evt = new KrollDict();
				IConstants adConstants = adContext.getConstants();
				evt.put("prerolls", loadSlot(adConstants.TIME_POSITION_CLASS_PREROLL()));
				evt.put("midrolls", loadSlot(adConstants.TIME_POSITION_CLASS_MIDROLL()));
				evt.put("postrolls", loadSlot(adConstants.TIME_POSITION_CLASS_POSTROLL()));
				fireEvent("onadresponse", evt);
			}
		});

		adContext.addEventListener(adConstants.EVENT_SLOT_STARTED(), new IEventListener() {
			public void run(final IEvent event) {
				/*
				 * TODO: should contain these keys: [NSDictionary dictionaryWithObjectsAndKeys: ads, @"ads", nil];
				 */
				fireEvent("onslotstarted", new KrollDict());
			}
		});
		adContext.addEventListener(adConstants.EVENT_SLOT_ENDED(), new IEventListener() {
			public void run(final IEvent event) {
				fireEvent("onslotended", new KrollDict());
			}
		});

		adContext.addEventListener(adConstants.EVENT_REQUEST_CONTENT_VIDEO_PAUSE(), new IEventListener() {
			public void run(final IEvent event) {
				currentPlayer.pause();
				adContext.setVideoState(adConstants.VIDEO_STATE_PAUSED());
				//currentPlayer.hide();
			}
		});
		adContext.addEventListener(adConstants.EVENT_REQUEST_CONTENT_VIDEO_RESUME(), new IEventListener() {
			public void run(final IEvent event) {
				currentPlayer.play();
				adContext.setVideoState(adConstants.VIDEO_STATE_PLAYING());
			}
		});

		// TODO: iOS listens for the ad "opening", but we don't have a literal translation on Android: it's probably LOADED or STARTED.
		adContext.addEventListener(adConstants.EVENT_AD_LOADED(), new IEventListener() {
			public void run(final IEvent event) {
				fireEvent("onadopen", new KrollDict());
			}
		});
		adContext.addEventListener(adConstants.EVENT_ERROR(), new IEventListener() {
			public void run(final IEvent event) {
				fireEvent("onadresponseerror", new KrollDict());
			}
		});

		// request temporal slots here
		// adContext.setVideoPlayer(9001);
		// adContext.setVideoAsset("android_videoAds", 500, null, true, 0, 0, 0, 0);
		// adContext.setCapability(adConstants.CAPABILITY_SLOT_TEMPLATE(), adConstants.CAPABILITY_STATUS_OFF());

		adContext.addTemporalSlot("pre", adConstants.ADUNIT_PREROLL(), 0, null, 0, 0, null, null, 0);
		adContext.addTemporalSlot("mid", adConstants.ADUNIT_MIDROLL(), 10, null, 0, 0, null, null, 0);
		adContext.addTemporalSlot("post", adConstants.ADUNIT_POSTROLL(), 100, null, 0, 0, null, null, 0);

		// TODO: this probably works (for generating a random 3 character id). Not sure though...
		Random rnd = new Random();
		char[] rawCustomId = { Character.toChars(65 + rnd.nextInt(25))[0], Character.toChars(48 + rnd.nextInt(9))[0],
				Character.toChars(65 + rnd.nextInt(25))[0] };
		String customId = new String(rawCustomId);
		adContext.addVideoPlayerNonTemporalSlot(customId, null, 300, 50, null, true, null, null);

		// TODO: we need to pass in a SurfaceDisplay to "registerVideoDisplay", and it MUST be a child of a FrameLayout!
		//adContext.registerVideoDisplay(currentPlayer);

		adContext.submitRequest(2);
	}

	@Kroll.method(runOnUiThread = true)
	public void playAds(KrollDict args) {
		int time = args.getInt("time");

		currentPlayer.pause();

		ArrayList<ISlot> temporalSlots = adContext.getTemporalSlots();
		for (int i = 0; i < temporalSlots.size(); i++) {
			ISlot slot = temporalSlots.get(i);
			// Note that we don't do exact equality, but check if it is close enough to the provided time.
			if (slot.getTimePosition() - time < 0.1) {
				slot.play();
				return;
			}
		}
	}
}